config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/index'

  devise_for :users

  resources :line_items
  resources :carts
  resources :stores

  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchase_complete'
  get 'gallery/search'
  post 'gallery/search'
end

app/models/store.rb
class Store < ApplicationRecord
  has_one_attached :product_image

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    if current_user && !current_user.admin?
      render "home/index"
    else 
      @store = Store.new
    end 
  end

  # GET /stores/1/edit
  def edit
    if current_user && !current_user.admin?
      render "home/index"
    end
  end

  # POST /stores or /stores.json
  def create
    if  current_user && !current_user.admin?
      render "home/index"
    else 
      @store = Store.new(store_params)

      respond_to do |format|
        if @store.save
          format.html { redirect_to @store, notice: "Store was successfully created." }
          format.json { render :show, status: :created, location: @store }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    if current_user && current_user.admin?
      respond_to do |format|
        if @store.update(store_params)
          format.html { redirect_to @store, notice: "Store was successfully updated." }
          format.json { render :show, status: :ok, location: @store }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    else 
       render "home/index"
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    if current_user && !current_user.admin?
      render "home/index"
    else 
      @store.destroy
      respond_to do |format|
        format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :price, :size, :product_image)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>
  <div class="field">
    <%= form.label :product_image %>
    <%= form.file_field :product_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<% if current_user.admin?%>
    <%= link_to 'Show', @store %> |
    <%= link_to 'Back', stores_path %>
<% end %>

app/views/stores/index.html.erb
<%= render 'layouts/menu'%>
<p id="notice"><%= notice %></p>

<div class='ui container' style="margin-top:6rem;">

 <table  class="ui teal striped table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td>
          <% if store.product_image.attached? %>
            <%= image_tag(store.product_image, style: 'height:50%; width:50%;')  %>
          <% end %>
        </td>
        <td><%= store.name %></td>
        <td><%= store.price %></td>
        <td><%= store.size %></td>
        <td><%= link_to 'Show', store %></td>
        <% if current_user && current_user.admin?%>
          <td><%= link_to 'Edit', edit_store_path(store) %></td>
          <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin?%>
<%= link_to 'New Store', new_store_path %>
<% end %>


</div>
</div>

app/views/stores/new.html.erb
<h1 style="margin-top: 6rem">New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p  style="margin-top: 6rem">
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @store.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @store.size %>
</p>
<p>
  <% if @store.product_image.attached? %>
    <%= image_tag(@store.product_image, style: 'height:50%; width:50%;')  %>
    <% end %>
</p>
<% if current_user.admin?%>
  <%= link_to 'Edit', edit_store_path(@store) %> |
  <%= link_to 'Back', stores_path %>
<% end %>