config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/index'

  devise_for :users

  resources :line_items
  resources :carts
  resources :stores

  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchase_complete'
  get 'gallery/search'
  post 'gallery/search'
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, :dependent => :destroy

    def add_product(store_id)
        puts "---------store id-------"
        puts store_id
        puts "---------store end id-------"

        current_item = line_items.find_by_store_id(store_id)
        if current_item
            current_item.quantity += 1
        else 
            current_item = line_items.build(:store_id => store_id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum {|item| item.total_price}
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to @cart, notice=> "Invalid Cart"
    else
      # respond_to do |format|
      #   format.html
      # end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to '/gallery/index', notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<!--<table style="margin-top: 6rem">-->
<!--<div class="ui segment">-->
<!--  <div class="ui two column very relaxed grid">-->
<!--    <div class="column">-->
      <%#= render(@cart.line_items) %>

<!--    </div>-->
<!--    <div class="column">-->
<!--      <tr>-->
<!--        <td>-->
<!--          Total-->
<!--        </td>-->
<!--        <td>-->

          <%#= number_to_currency(@cart.total_price) %>

<!--        </td>-->
<!--      </tr>-->
      <%# session[:amount] = @cart.total_price %>
      <%#= link_to "Empty Cart", cart_path, :method => :delete, :confirm => "Are you sure?" %>
<!--      <p>-->
        <%# link_to "Continue Shopping", :controller => "gallery", :action => "index" %>
        <%#  if user_signed_in? %>
          <%#= link_to "Checkout", :controller => "gallery",:action => "checkout" %>
        <%#else  %>
          <%#= link_to "Checkout", new_user_session_path %>
        <%#end  %>
<!--      </p>-->
<!--    </div>-->
<!--  </div>-->
<!--  <div class="ui vertical divider">-->
<!--    and-->
<!--  </div>-->
<!--</div>-->
<!--</table>-->

<h2 class="ui center aligned icon header" style="margin-top: 6rem">
  <i class=" orange shopping cart icon"></i>
  Your Shopping Cart
</h2>
<div class="ui container">
  <table class="ui very basic  celled table" >
    <thead>
    <tr>
      <th>Products</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
    </thead>
    <tbody>
    <%= render(@cart.line_items) %>
    </tbody>
    <tfoot class="full-width">
    <tr>
      <th></th>
      <th colspan="4">
        <% session[:amount] = @cart.total_price %>
        <%  if user_signed_in? %>
            <%= link_to  :controller => "gallery",:action => "checkout" do %>
              <div class="ui right floated small primary labeled icon button">
                    <i class="rupee sign icon"></i>
                    <%= number_to_currency(@cart.total_price) %>
              </div>
            <% end %>
          <%else  %>
            <%= link_to  new_user_session_path  do %>
              <div class="ui right floated small primary labeled icon button">
                <i class="rupee sign icon"></i>
                <%= number_to_currency(@cart.total_price) %>
              </div>
            <% end %>
          <%end  %>
        <%= link_to  cart_path, :method => :delete do %>
            <div class="ui red small button">
              Empty Cart
            </div>
        <% end %>

      </th>
    </tr>
    </tfoot>
  </table>

</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%#= render 'carts/cart' %>
<%= render :partial => 'carts/cart'%>