config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/index'

  devise_for :users

  resources :line_items
  resources :carts
  resources :stores

  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchase_complete'
  get 'gallery/search'
  post 'gallery/search'
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  before_action :authenticate_user!
    
  def index
    @gallery = Store.all
  end
  def checkout
    if request.post?
      amount = session[:amount]
      ActiveMerchant::Billing::Base.mode = :test

      # Create a new credit card object
      credit_card = ActiveMerchant::Billing::CreditCard.new(
        :number     => params[:number],
        :month      => params[:month],
        :year       => params[:year],
        :first_name => params[:first_name],
        :last_name  => params[:last_name],
        :verification_value  => params[:verification_value]
      )

      if credit_card.valid?
        # Create a gateway object to the TrustCommerce service
        gateway = ActiveMerchant::Billing::TrustCommerceGateway.new(
          :login    => 'TestMerchant',
          :password => 'password'
        )

        # Authorize for $10 dollars (1000 cents)
        response = gateway.authorize(amount.to_i, credit_card)

        if response.success?
          # Capture the money
          session[:cart] = nil
          gateway.capture(amount.to_i, response.authorization)
          redirect_to :action => :purchase_complete
        else
          flash[:notice] = "Invalid credit cart details. Give the correct inputs!"
          render :action => :checkout
        end
      end
    end
  end

  def search
    keyword="%" + params[:search].to_s + "%"
    @gallery = Store.find_by_sql ["SELECT * FROM stores WHERE name LIKE ? ",keyword]
    puts "--------@gallery------------"
    puts @gallery.inspect
    puts "--------@gallery------------"
  end

end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/_products_gallery.html.erb
<div class='ui  container' style="margin-top:6rem;">
  <div class='ui grid '>
    <div class="ui link cards ">
      <% @gallery.each do |item| %>
        <div class="card ">
          <div class="ui fluid image">
            <% if item.product_image.attached? %>
              <%= image_tag(item.product_image, style: 'height:100%; width:100%;')  %>
            <% end %>
          </div>

          <div class="content">
            <div class="header"><%= item.name %></div>
            <div class="meta">
              <a>category</a>
            </div>
            <div class="description">
              <lable>Size : </lable>
              <%= item.size%>
            </div>
          </div>
          <div class="extra content">
            <%= link_to line_items_url(:store_id => item.id), :method => :post do %>
              <div class="ui fluid labeled button" tabindex="0">
                <div class="ui red fluid button">
                  <i class="cart arrow down icon"></i> Add To Cart
                </div>
                <a class="ui basic  red left pointing label">
                  <i class="rupee sign icon"></i><%= item.price%>
                </a>
              </div>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/gallery/checkout.html.erb
<div class="div ui  container" style="margin-top: 6rem">
  <%= session[:amount] %>
  <%= form_with local: true do |form| %>
  <div class="ui form">
    <h4 class="ui dividing header">Check out</h4>
    <div class="field">
      <%= form.label :first_name %>
      <div class="two fields">
        <div class="field">
          <%= form.text_field :first_name, placeholder:'First Name' %>
        </div>
        <div class="field">
          <%= form.text_field :last_name, placeholder:'Last Name' %>
        </div>
      </div>
    </div>
    <h4 class="ui dividing header">Billing Information</h4>
    <div class="fields">
      <div class="seven wide field">
        <%= form.label :number %>
        <%= form.text_field :number, placeholder:'Card #', maxlength:"16" %>
      </div>
      <div class="three wide field">
        <%= form.label :CVC %>
        <%= form.text_field :verification_value, maxLength:"3", placeholder:"CVC" %>
      </div>
      <div class="six wide field">
        <%= form.label :Expiration %>
        <div class="two fields">
          <div class="field">
            <select class="ui fluid search dropdown" name="month">
              <option value="">Month</option>
              <option value="1">January</option>
              <option value="2">February</option>
              <option value="3">March</option>
              <option value="4">April</option>
              <option value="5">May</option>
              <option value="6">June</option>
              <option value="7">July</option>
              <option value="8">August</option>
              <option value="9">September</option>
              <option value="10">October</option>
              <option value="11">November</option>
              <option value="12">December</option>
            </select>
          </div>
          <div class="field">
            <%= form.text_field :year, placeholder:'Year', maxLength:"4" %>
          </div>
        </div>
      </div>
    </div>
    <%= form.submit "Submit Order", class:"ui button", id:'check-out-btn' %>

  </div>
    <%end %>
</div>

app/views/gallery/index.html.erb
<%= render 'layouts/menu'%>
<%= render 'products_gallery'%>

app/views/gallery/purchase_complete.html.erb
<div  style="margin-top: 6rem">
  <div class="ui header">
    Thank you for shopping with us!
  </div>
  <div class="content">
    <p>
      your order has been processed.<br />
      A detailed email has been sent.<br />
      <a href="/gallery/index">Click here to continue the shopping</a>
    </p>
  </div>
</div>

app/views/gallery/random.html.erb
<h1>random</h1>

app/views/gallery/search.html.erb
<h1 style="margin-top: 6rem"> Search Results</h1>

<%= render 'products_gallery'%>